### PR TITLE
Port to sphinx 2.x

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by jonascj** [comment]
So how do we proceed from here? Should we ask for admin privileges to be able to merge?

**Comment by dhellmann** [comment]
@jonascj I've made you an admin (or at least invited you to be). I'll leave it up to you to decide who else to add to the repo. Use your powers for good. ;-)

**Comment by t-b** [comment]
@jonascj Merge?

**Comment by jonascj** [comment]
Sorry, email notifications were turned off. Give me a day or two to read up on the status of things. But yes, I guess so.

**Comment by spinus** [comment]
This patch looks really good. Cheers.

**Comment by m1no** [comment]
PR looks good for me too. @jonascj thanks for taking over the maintainer here.

**Comment by rixx** [comment]
For everybody else waiting for this PR, this is the line to use it directly in your requirements.txt or with pip:

```
git+https://github.com/t-b/sphinxcontrib-images@port-to-sphinx-2.x
```

**Comment by jonascj** [comment]
I'm not sure I ever intended to become the maintainer... I would like to, but I need some help moving forward. 

Any preferences on merge commit vs. squash+merge vs. rebase+merge?

Can we skip further reviews? It passes the Travis-build for various versions, so to me everything seems good.

**Comment by t-b** [comment]
My preference is `merge commit`.
I'm okay with merging as is.

Do you have the credentials for https://pypi.org/ for uploading a new package version?

**Comment by jonascj** [comment]
I don't think we ever got the pypi.org creddentials from @spinus .

Do we wish to use https://pypi.org/project/sphinxcontrib-images/ going forward? Or is there another better package name now under the sphinx-contrib/images umbrella?

**Comment by t-b** [comment]
If possible I would favour using the existing package name in order to make it hassle-free for the user.

**Comment by jonascj** [comment]
I went back through the old PR conversations and e-mails. Privileges on https://pypi.org/project/sphinxcontrib-images/ were never transferred or credentials shared. I've contacted @spinus about this.

The old conversations revealed that the package was prepared manually and manually uploaded to pypi.org. I'll do that again once I have access.

**Comment by spinus** [comment]
done. Let me know if I should add anyone else. Cheers

**Pull request merged**
