### PR TITLE
.travis.yml: Update to latest sphinx and python versions

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by t-b** [comment]
@jonascj I would say the current coverage of sphinx versions should be enough. But I added 2.2 and 2.1 nevertheless.

**Comment by jonascj** [comment]
I'll get to this tomorrow. Maybe we should so something about Sphinx 3?

**Comment by t-b** [comment]
@jonascj Done.

**Comment by jonascj** [comment]
Great work, cheers!

**Pull request merged**
